#!/bin/sh

APPEND_SCRIPT="${XDG_DATA_HOME:-$HOME/.local/share}/rofi/append_video.sh"
DOWNLOAD_OUTPUT="$HOME/Videos/YouTube/%(uploader)s/%(title)s.%(ext)s"

_err_msg() {
    [ -n "$1" ] && printf '\000message\037error: %s\n \000nonselectable\037true\n' "$1"
    exit 1
}

_download_vid() {
    notify-send -i rofi -a "${3:-mpv_rofi_utils}" "⬇️Start downloading '$2'..."
    qid="$(tsp yt-dlp "$1" -o "$DOWNLOAD_OUTPUT")"
    tsp -D "$qid" notify-send -i rofi -a "${3:-mpv_rofi_utils}" "✅Download done: '$2'" >/dev/null 2>&1
}

_play() { [ -n "$1" ] && setsid -f mpv "$1" >/dev/null 2>&1; }

_append() {
    [ -f "$APPEND_SCRIPT" ] || _err_msg "append script not found in '$APPEND_SCRIPT'"
    [ -n "$1" ] && setsid -f "${APPEND_SCRIPT}" "$1" >/dev/null 2>&1
}
